### ISSUE TITLE
Version on crates.io does not work with the version of failure

### ISSUE THREAD

**Issue by sdroege** [withoutboats/derive-fail#1]
failure_derive on crates.io assumes that Backtrace and Cause both exist, but the failure crate on crates.io does not have that yet. The versions from GIT work fine together.

**Comment by withoutboats** [comment]
The version of failure on crates.io is a placeholder. This crate has not been released on crates.io yet.

**Comment by sdroege** [comment]
There's https://crates.io/crates/failure_derive. But OK :)

**Comment by Deedasmi** [comment]
Reserved name so nobody else claims it :)
