### ISSUE TITLE
Update to quote has broken failure_derive

### ISSUE THREAD

**Issue by AlexApps99** [withoutboats/derive-fail#13]
```
error[E0433]: failed to resolve: could not find `__rt` in `quote`
   --> /home/lxb/.cargo/registry/src/github.com-1ecc6299db9ec823/failure_derive-0.1.6/src/lib.rs:107:70
    |
107 | fn display_body(s: &synstructure::Structure) -> Result<Option<quote::__rt::TokenStream>, Error> {
    |                                                                      ^^^^ could not find `__rt` in `quote`
```

**Comment by jrandall** [comment]
The cause appears to be this commit: https://github.com/dtolnay/quote/commit/41543890aa76f4f8046fffac536b9445275aab26

In which the name is changed from `__rt` to `__private` to clarify that although it is marked `pub` it is not intended to be a public interface.

**Comment by kentfredric** [comment]
I'd file a contra bug for this in quote, because even though its not quotes fault, the rust ecosystem has started to break until failures_derive unbreaks its code. But I'm not allowed to open bugs on quote ... 

So the best I can do is @dtolnay and hope he sees it.

**Comment by wdanilo** [comment]
Everything is in fire now on our side as well :D

**Comment by jrandall** [comment]
I'm not sure what is going on here, as nowhere in the failure_derive crate is the `__rt` namespace mentioned, but the error appears to be caused by a reference to it.

Perhaps a macro from the quote crate is accidentally exposing the `__rt` namespace instead of the new `__private` namespace?

**Comment by normano** [comment]
Wrong repository.

https://github.com/rust-lang-nursery/failure/blob/master/failure_derive/Cargo.toml

Fix: https://github.com/rust-lang-nursery/failure/pull/343

**Comment by kentfredric** [comment]
Worth mentioning that the Cargo metadata cited, still says:
```toml
repository = "https://github.com/withoutboats/failure_derive"
```

Which says that _here_ is the right place to report bugs. If _here_ is no longer the right place, that also needs fixing.

**Comment by normano** [comment]
Submit a pull request to fix what you think is wrong. Wrong place to talk about it.

**Comment by infinity0** [comment]
Saying stuff is wrong without saying why you think it's wrong or offering what you think is the right alternative, isn't a helpful style of communication.

**Comment by AlexApps99** [comment]
Should this issue be closed, since https://github.com/rust-lang-nursery/failure/issues/342 seems to be the correct place to raise this?

**Comment by kornelski** [comment]
In case anyone wants a quick workaround, add this to your `Cargo.toml`'s dependencies:

```toml
quote = "=1.0.2"
```

**Comment by kentfredric** [comment]
> Submit a pull request to fix what you think is wrong

I'd like to file a PR to revert the change in quote asap, or have quote 1.0.3 yanked until this problem can be fixed for real, ... but due to both issues and PR's being something that is disabled for "non contributors" on the quote repo, there pretty much *isnt* a right place to do this. 

(FWIW: Not grumping at you, just annoyed at the whole situation being made needlessly more difficult)

**Comment by AlexApps99** [comment]
Closing this because of rust-lang-nursery/failure#342.
