### ISSUE TITLE
no_std support

### ISSUE THREAD

**Issue by quininer** [withoutboats/derive-fail#2]
Currently using `#[derive(Fail)]` in `no_std` will cause a compilation error.

```
error[E0433]: failed to resolve. Maybe a missing `extern crate std;`?
  --> src/lib.rs:26:17
   |
26 | #[derive(Debug, Fail)]
   |                 ^^^^ Maybe a missing `extern crate std;`?

error: cannot continue compilation due to previous error
```

This is caused by [hardcoded `std` in `failure_derive`](https://github.com/withoutboats/failure_derive/blob/master/src/lib.rs#L34).

I think manual `use core as std;` is not an elegant solution.
We can provide an `no_std` feature, or add `option`/`fmt` alias to `failure`.

**Comment by withoutboats** [comment]
The 0.1.1 release should support no_std. :tada:
